### ISSUE TITLE
Error: Cannot find module './providers/twitchProvider'

### ISSUE THREAD

**Issue by insanity54** [sammwyy/twitch-fetcher#1]
Hi there. I'm trying out this module and I think I found a bug.

Here is how I am using this lib

```
const TwitchFetcher = require('twitch-fetcher');

class EmoteSet {
    constructor (params) {
        const { clientId, OAuth, channel} = params;
        if (typeof clientId === 'undefined') throw new Error('clientId passed to EmoteSet must be defined, but it was undefined.')
        if (typeof OAuth === 'undefined') throw new Error('OAuth passed to EmoteSet must be defined, but it was undefined.')
        if (typeof channel === 'undefined') throw new Error('channel passed to EmoteSet must be defined, but it was undefined.')

        this.channel = channel;
        this.fetcher = new TwitchFetcher({
            clientId,
            OAuth
        });
        return this;
    }


    async generate () {
        console.log(`getting userID of ${this.channel}`);
        const { id } = await fetcher.getuserData({ username: this.channel })

        console.log('downloading 7tv emotes');
        const emotes7tv = await this.fetcher.getEmotesByID(id, { "7tv": true });
        console.log(emotes7tv);

        console.log('downloading bttv emotes');
        const emotesBttv = await this.fetcher.getEmotesByID(id, { "bttv": true });
        console.log(emotesBttv);

        console.log('downloading ffz emotes');
        const emotesFfz = await this.fetcher.getEmotesByID(id, { "ffz": true });
        console.log(emotesFfz);

        console.log('downloading Twitch emotes');
        const emotesTwitch = await this.fetcher.getEmotesByID(id, { "twitch": true });
        console.log(emotesTwitch);
    }
}


module.exports = EmoteSet
```

Here is the error I'm seeing

```
Error: Cannot find module './providers/twitchProvider'
Require stack:
- /home/chris/Documents/foukbot/node_modules/twitch-fetcher/lib/module.js
- /home/chris/Documents/foukbot/node_modules/twitch-fetcher/lib/index.js
- /home/chris/Documents/foukbot/srv/external/EmoteSet.js
- /home/chris/Documents/foukbot/web.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chris/Documents/foukbot/node_modules/twitch-fetcher/lib/module.js:24:46)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/chris/Documents/foukbot/node_modules/twitch-fetcher/lib/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/chris/Documents/foukbot/node_modules/twitch-fetcher/lib/module.js',
    '/home/chris/Documents/foukbot/node_modules/twitch-fetcher/lib/index.js',
    '/home/chris/Documents/foukbot/srv/external/EmoteSet.js',
    '/home/chris/Documents/foukbot/web.js'
  ]
}
Program node ./web.js exited with code 1
```

I think the problem is a misspelled module name.

https://github.com/enhancedtwitch/twitch-fetcher/blob/cc0c6d21922fad75a363b3fe452a9538ca2aba7c/lib/module.js#L24

**Comment by sammwyy** [comment]
Thank you for your PR.
